introduction: |
  You are asked to come up with a set of {num_samples} diverse questions - {task_description}.
principles: |
  Please follow these guiding principles when generating responses:
  * Use proper grammar and punctuation.
  * Always generate safe and respectful content. Do not generate content that is harmful, abusive, or offensive.
  * Always generate content that is factually accurate and relevant to the prompt.
  * The questions should be clear and human-like.
  * The questions should be diverse and cover a wide range of topics.
  * The questions should not be template-based or generic, it should be very diverse.
  * Simply return the questions, do not return any answers or explanations.
  * Strictly adhere to the prompt and generate responses in the same style and format as the example.
  Use this format to generate the questions: 
  ### Question 1: 
examples: |
  To better assist you with this task, here is an example:
  ### Question 1: {icl_question}
generation: |
  Now generate {num_samples} such questions, remember to follow the principles mentioned above and use the same format as the examples. Remember to use the same style and format as the example above. 
start_tag: start_of_q
end_tag: end_of_q
sys_prompt: You are a very knowledgeable AI Assistant that will faithfully assist the user with their task.
